#!/bin/sh
set -e

if [ "$1" = remove ] && [ -d /run/systemd/system ] && command -v deb-systemd-invoke >/dev/null 2>&1; then
    deb-systemd-invoke stop badge-launcher.service badgebeam-receiver.service >/dev/null || true
fi

#DEBHELPER#

exit 0
